language: node_js
install:
  - npm install -g codecov
  - npm install -g istanbul
  - npm install -g mocha
script:
  - istanbul cover mocha --report lcovonly -- -R spec
  - codecov
node_js:
  - 'node'
  - '6'
after_success:
  - bash <(curl -s https://codecov.io/bash)

