language: node_js
install:
  - npm install
  - npm install -g codecov
  - npm install -g istanbul
node_js:
  - 'node'
  - '6'
after_success:
  - bash <(curl -s https://codecov.io/bash)
script:
  - istanbul cover node_modules/mocha/bin/_mocha && codecov

