language: node_js
install:
  - npm install -g codecov
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
  - codecov
node_js:
  - 'node'
  - '6'
after_success:
  - bash <(curl -s https://codecov.io/bash)

